# Generated by Django 4.1.1 on 2022-12-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('unique_code', models.IntegerField()),
                ('size', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30')], max_length=200)),
                ('mainchoice', models.CharField(choices=[('low', 'low'), ('high', 'hgih'), ('medium', 'medium')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='tryapp.productmainmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chice_color', models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('black', 'black')], max_length=200)),
                ('product', models.ManyToManyField(related_name='color', to='tryapp.productmainmodel')),
            ],
        ),
    ]
